[package]
name = "sakura-secure-client"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.40"
color-eyre = "0.6.3"
crossterm = "0.28.1"
env_logger = "0.11.6"
log = "0.4.25"
ratatui = "0.29.0"
serde = { version = "1.0.217", features = ["derive"] }
ssh2 = "0.9.4"
